# Generated by Django 2.1.5 on 2019-05-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0003_auto_20190511_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sparkling',
            field=models.CharField(choices=[('ST', 'Still'), ('SP', 'Sparkling'), ('FL', 'Flavoured')], max_length=20),
        ),
    ]
