# Generated by Django 2.1.5 on 2019-05-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0004_auto_20190511_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bottle',
            field=models.CharField(choices=[('PL', 'Plastic'), ('GL', 'Glass')], max_length=30),
        ),
    ]
