# Generated by Django 2.1.5 on 2019-05-11 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordermanagement', '0005_auto_20190511_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_order', models.DateTimeField()),
                ('ordered_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_shipment_date', models.DateField()),
                ('shipment_status', models.CharField(choices=[('Act.', 'Active'), ('Canc.', 'Cancelled'), ('Done', 'Shipped')], max_length=64)),
                ('user_originator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderitems',
            name='linked_shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordermanagement.Shipment'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordermanagement.Product'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='ordering_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
