# Generated by Django 2.1.5 on 2019-05-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0007_auto_20190511_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bottle',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Glass', 'Glass')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='sparkling',
            field=models.CharField(choices=[('Still', 'Still'), ('Sparkling', 'Sparkling'), ('Flavoured', 'Flavoured')], max_length=20),
        ),
    ]
